package sbecom.model;

import java.math.BigDecimal;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Lob;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Date;

@Entity
@Data // Lombok annotation to generate getters, setters, toString, equals, and hashCode methods automatically
@AllArgsConstructor // Lombok annotation to generate a constructor with all fields as parameters, why? —> For easy instantiation of the class with all attributes
@NoArgsConstructor // Lombok annotation to generate a no-argument constructor; why? —> Required by JPA
public class Product {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) //this annotation is used to specify that the primary key value will be automatically generated by the database using an identity column. This means that the database will handle the generation of unique identifiers for new records, typically by auto-incrementing the value for each new entry.
    private int id;
    private String name;
    private String description;
    private String brand;
    private BigDecimal price; // Using BigDecimal for monetary values to avoid floating-point precision issues
    private int stockQuantity;
    private Date releaseDate;
    private boolean productAvailable;
    private String imageName;
    private String imageType;
    private String category;
    @Lob // Specifies that the field should be treated as a Large Object, suitable for storing large binary data
    private byte[] imageData;

    public Product(int id) {
        this.id = id;
    }
}
